# Generated by Django 5.1.1 on 2024-11-15 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowrecord",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_records",
                to="system.book",
            ),
        ),
        migrations.AlterField(
            model_name="borrowrecord",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_records",
                to="system.member",
            ),
        ),
    ]
