# Generated by Django 5.1.1 on 2024-11-16 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_alter_borrowrecord_book_alter_borrowrecord_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowrecord",
            name="borrow_date",
            field=models.DateField(default=datetime.date(2024, 11, 16)),
        ),
    ]
