# Generated by Django 5.1.1 on 2024-10-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_post_author"),
        ("posts", "0006_alter_post_author"),
    ]

    operations = []
